board_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
	url(r'^board/', include('imgboard.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

imgboard/urls.py
from django.conf.urls import url

from . import views

app_name = 'imgboard'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^thread(?P<thread_id>[0-9]+)/$', views.ThreadView.as_view(), name='thread')
]

imgboard/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

class Thread(models.Model):
	date_created = models.DateTimeField(default=timezone.now)
	thread_name = models.CharField(max_length=50)
	bump_thread = models.IntegerField(default=0)

class Post(models.Model):
	thread = models.ForeignKey(Thread)
	date_published = models.DateTimeField('date published')
	post_text = models.CharField(max_length=300)
	pic = models.ImageField(upload_to='pics', blank=True)

imgboard/forms.py
from django import forms

class PostForm(forms.Form):
	post_text = forms.CharField(label='Enter your message here', max_length=300)
	picture = forms.ImageField(label='', required=False)

class ThreadForm(forms.Form):
	thread_name = forms.CharField(label='Name of new thread', max_length=50)

imgboard/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.base import View
from django.utils import timezone

from .models import Thread, Post
from .forms import PostForm, ThreadForm


class IndexView(View):
	thread_form = ThreadForm
	initial = {'key': 'value'}

	def get(self, request, **kwargs):
		form = self.thread_form(initial=self.initial)
		thread_list = Thread.objects.all().order_by('-bump_thread', '-id')
		context = {'thread_list': thread_list,
					'form': form,
		}
		return render(request, 'index.html', context)


	def post(self, request):
		form = self.thread_form(request.POST)
		if form.is_valid():
			t = Thread(thread_name=form.cleaned_data['thread_name'])
			t.save()
			past = timezone.datetime.today() - timezone.timedelta(days=14)
			Thread.objects.filter(date_created__lte=past).delete()
		return HttpResponseRedirect('/board')


class ThreadView(View):
	post_form = PostForm
	initial = {'key': 'value'}

	def get(self, request, thread_id, **kwargs):
		thread = get_object_or_404(Thread, pk=thread_id)
		form = self.post_form(initial=self.initial)
		context = {
			'thread': thread,
			'form': form,
		}
		return render(request, 'thread.html', context)

	def post(self, request, **kwargs):
		valid_bump_variants = ('bump', 'Bump', 'Bump', 'bump!')
		form = self.post_form(request.POST, request.FILES)
		if form.is_valid():
			p = Post(post_text=form.cleaned_data['post_text'],
				date_published=timezone.now(), thread_id=kwargs['thread_id'])
			p.pic = request.FILES.get('picture', '')
			p.save()
			thread = get_object_or_404(Thread, pk=kwargs['thread_id'])
			if p.post_text in valid_bump_variants and Post.objects.filter(thread=kwargs['thread_id']).count() < 100:
				thread.bump_thread += 1
				thread.save()
		return HttpResponseRedirect('/board/thread' + kwargs['thread_id'])

imgboard/templates/imgboard/thread.html
<h2>{{ thread.thread_name }}</h2>
<a href="{% url 'imgboard:index' %}">Back to threads</a>
<div>
	<form method="post">
  	{% csrf_token %}
    {{ form }}
    <input type="submit" value="Send" />
  </form>
</div>
<ul>
{% for post in thread.post_set.all %}
	<h4>{{ post.date_published }}</h4>
	<h3>{{ post.post_text }}</h3>
---------------------------------
{% endfor %}
</ul>

imgboard/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>imgboard</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'imgboard/index_style.css' %}" </>
{% load staticfiles %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid text-center">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
    </div>
    <div class="col-sm-8 text-left">
      <h2>Welcome to the board. Create your own theme or chose one from the list.</h2>
      <hr>
      {% if thread_list %}
        <div>
          {% for thread in thread_list %}
            <a href="{% url 'imgboard:thread' thread.id %}"><div id="thread_list"><h4>{{ thread.thread_name }}</h4></div></a>
          {% endfor %}
        </div>
      {% else %}
        <p>No threads are available.</p>
      {% endif %}
    </div>
    <div class="col-sm-2 sidenav">
      <div class="well">
        <form method="post">
          {% csrf_token %}
          {{ form }}
          <input type="submit" value="Create"/>
        </form=>
      </div>
      <div class="well">
        <p>ADS</p>
      </div>
    </div>
  </div>
</div>


<footer class="container-fluid text-center">
  <p>Footer Text</p>
</footer>

</body>
</html>

imgboard/templates/thread.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>thread/: {{ thread.thread_name }}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'imgboard/thread_style.css' %}" </>
{% load staticfiles %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid text-center">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <p><a href="{% url 'imgboard:index' %}">Back to threads</a></p>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
    </div>
    <div class="col-sm-8 text-left">
      <h2>{{ thread.thread_name }}</h2>
      <hr>
      {% for post in thread.post_set.all %}
        <div>
          <h4>{{ post.date_published }}</h4>
          <p>{{ post.post_text }}</p>
          {% if post.pic %}
  					<img src="{{ post.pic.url }}">
  			  {% endif %}
          <hr>
        </div>
      {% endfor %}
    </div>
    <div class="col-sm-2 sidenav">
      <div class="well">
        <form method="post" enctype="multipart/form-data">
			  	{% csrf_token %}
			    {{ form }}
			    <input type="submit" value="Send" />
			  </form>
      </div>
      <div class="well">
        <p>ADS</p>
      </div>
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p>Footer Text</p>
</footer>

</body>
</html>